#- name: Install OpenJDK
#  yum: name=java-1.7.0-openjdk state=present


#- name: Change ownership on monasca download directory.
#  become: yes
#  file: path="{{monasca_download_dir}}" state=directory owner=zookeeper group=zookeeper recurse=yes


- name: Create analytics user
  become: yes
  user:
    name: zookeeper


- name: Create zookeeper inst path
  become: yes
  file: path="{{ zookeeper_dir }}" recurse=yes owner=zookeeper mode=0755  state=directory


- name: Create zookeeper data path
  become: yes
  file: path="{{ zookeeper_data_dir }}" recurse=yes owner=zookeeper mode=0755  state=directory


- name: Create zookeeper log path
  become: yes
  file: path="{{ zookeeper_log_dir }}" recurse=yes owner=zookeeper mode=0755  state=directory


- name: Change ownership on zokeeper directory Redhat
  become: yes
  file: path="{{zookeeper_dir}}" state=directory owner=zookeeper group=zookeeper recurse=yes


- name: Download Zookeeper version
  get_url: url={{zookeeper_url}} dest={{zookeeper_dir}}/zookeeper-{{zookeeper_version}}.tar.gz timeout=100

- name: Unpack tarball
  command: tar xzf {{zookeeper_dir}}/zookeeper-{{zookeeper_version}}.tar.gz --strip-components=1 chdir={{zookeeper_dir}} creates={{zookeeper_dir}}/bin

- name: Setup Apache ZooKeeper service
  template: dest="/etc/systemd/system/zookeeper.service" src=zookeeper.service.j2
  register: zookeeper_service

- name: reload systemd
  command: /usr/bin/systemctl --system daemon-reload
  when: zookeeper_service | changed
